apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-deploy
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: go-demo
      version: v1
  template:
    metadata:
      labels:
        app: go-demo
        version: v1
    spec:
      containers:
      - name: go-demo-pod
        image: arti.local:9094/k8s-docker-release-local/demo/go-demo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: sc-pvc
          mountPath: /opt
      volumes:
      - name: sc-pvc
        persistentVolumeClaim:
          claimName: test-pvc
      imagePullSecrets:
        - name: regcred-local
